services:
  django:
    build: .
    container_name: django_app
    command: gunicorn main.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: redis_server
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    container_name: celery_worker
    command: celery -A main worker -l info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - django

  celery_beat:
    build: .
    container_name: celery_beat
    command: celery -A main beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - django