# Generated by Django 5.2.5 on 2025-08-20 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productManagement', '0002_alter_categories_image_url_products_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
