# Generated by Django 5.2.5 on 2025-08-20 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productManagement', '0003_products_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100, null=True)),
                ('category_type', models.CharField(max_length=50, null=True)),
                ('is_active', models.IntegerField(default=1)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'title'},
        ),
        migrations.RemoveField(
            model_name='products',
            name='created_by_admin',
        ),
        migrations.AlterField(
            model_name='products',
            name='vendor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['title', 'title'], name='productMana_title_3d6a33_idx'),
        ),
    ]
