# Generated by Django 5.2.5 on 2025-08-20 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productManagement', '0004_units_alter_products_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Units',
            new_name='ProductMetaData',
        ),
    ]
