# Generated by Django 5.2.5 on 2025-08-20 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productManagement', '0005_rename_units_productmetadata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductMetaData',
        ),
    ]
