# Generated by Django 5.2.5 on 2025-08-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productManagement', '0006_delete_productmetadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(max_length=900, null=True)),
                ('category_type', models.CharField(max_length=50, null=True)),
                ('is_active', models.IntegerField(default=1)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
