# Generated by Django 5.2.5 on 2025-08-20 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productManagement', '0007_productmetadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmetadata',
            name='description',
        ),
    ]
