# Generated by Django 5.2.5 on 2025-08-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productManagement', '0008_remove_productmetadata_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmetadata',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
