# Generated by Django 5.2.5 on 2025-08-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productManagement', '0009_productmetadata_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmetadata',
            name='type',
            field=models.CharField(choices=[('category', 'Category'), ('unit', 'Unit')], default='category', max_length=255, null=True),
        ),
    ]
