# Generated by Django 5.2.5 on 2025-08-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productManagement', '0010_alter_productmetadata_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmetadata',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
