# Generated by Django 5.2.5 on 2025-08-20 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productManagement', '0011_alter_productmetadata_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={},
        ),
        migrations.RemoveField(
            model_name='products',
            name='vendor_id',
        ),
        migrations.AddField(
            model_name='products',
            name='created_by_admin',
            field=models.ForeignKey(blank=True, db_column='created_by_admin_id', limit_choices_to={'groups__name': 'Admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='products',
            name='vendor',
            field=models.ForeignKey(db_column='vendor_id', default=1, limit_choices_to={'groups__name': 'Vendor'}, on_delete=django.db.models.deletion.CASCADE, related_name='products_as_vendor', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='productManagement.categories'),
        ),
    ]
