# Generated by Django 5.2.5 on 2025-08-20 13:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productManagement', '0012_alter_products_options_remove_products_vendor_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='products',
            name='productMana_title_3d6a33_idx',
        ),
        migrations.RemoveField(
            model_name='products',
            name='created_by_admin',
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['title'], name='productMana_title_ed0fda_idx'),
        ),
    ]
