# Generated by Django 5.2.5 on 2025-08-20 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productManagement', '0013_remove_products_productmana_title_3d6a33_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='image_url',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, to='productManagement.categories'),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='vendor',
            field=models.ForeignKey(db_column='vendor_id', on_delete=django.db.models.deletion.CASCADE, related_name='products_as_vendor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='products',
            table='productManagement_products',
        ),
    ]
