# Generated by Django 5.2.5 on 2025-08-20 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productManagement', '0014_alter_categories_image_url_alter_products_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='vendor',
            field=models.ForeignKey(db_column='vendor_id', limit_choices_to={'groups__name': 'Vendor'}, on_delete=django.db.models.deletion.CASCADE, related_name='products_as_vendor', to=settings.AUTH_USER_MODEL),
        ),
    ]
