# Generated by Django 5.2.5 on 2025-08-20 16:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productManagement', '0015_alter_products_vendor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['product', '-created_at'], 'verbose_name_plural': 'Product Images'},
        ),
        migrations.AlterModelOptions(
            name='productmetadata',
            options={'ordering': ['sort_order', 'name'], 'verbose_name_plural': 'Product MetaData'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='categories',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productimage',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_images_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productimage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productmetadata',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_metadata_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='products',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', limit_choices_to={'role__in': ['admin', 'vendor']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='products',
            name='vendor',
            field=models.ForeignKey(db_column='vendor_id', limit_choices_to={'role': 'vendor'}, on_delete=django.db.models.deletion.CASCADE, related_name='products_as_vendor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['category'], name='productMana_categor_ea2805_idx'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['vendor'], name='productMana_vendor__493087_idx'),
        ),
    ]
