# Generated by Django 5.2.5 on 2025-08-13 20:55

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions', models.JSONField(blank=True, default=dict)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BuyerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address', models.TextField(blank=True, null=True)),
                ('secondary_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('delivery_instructions', models.TextField(blank=True, null=True)),
                ('preferred_delivery_time', models.CharField(blank=True, max_length=50, null=True)),
                ('loyalty_tier', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='bronze', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PROFILE_UPDATE', 'Profile Update'), ('PASSWORD_CHANGE', 'Password Change'), ('WALLET_CREDIT', 'Wallet Credit'), ('WALLET_DEBIT', 'Wallet Debit'), ('ORDER_PLACED', 'Order Placed'), ('ACCOUNT_LOCKED', 'Account Locked'), ('ACCOUNT_UNLOCKED', 'Account Unlocked'), ('EMAIL_VERIFIED', 'Email Verified'), ('PHONE_VERIFIED', 'Phone Verified'), ('OTHER', 'Other')], max_length=30)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(blank=True, max_length=100, null=True)),
                ('business_registration_number', models.CharField(blank=True, max_length=50, null=True)),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_account_info', models.JSONField(blank=True, default=dict)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('is_verified_vendor', models.BooleanField(default=False)),
                ('verification_documents', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='idx_user_role',
            old_name='accounts_us_role_1fa9a5_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='idx_user_username',
            old_name='accounts_us_usernam_c0ea66_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='idx_user_email',
            old_name='accounts_us_email_74c8d6_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='idx_user_phone',
            old_name='accounts_us_phone_f54457_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='idx_user_status',
            old_name='accounts_us_status_6bbe13_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='idx_user_wallet',
            old_name='accounts_us_wallet_76df32_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='idx_user_role_status',
            old_name='accounts_us_role_9fc6ca_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='idx_user_verification',
            old_name='accounts_us_email_v_262863_idx',
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='buyerprofile',
            index=models.Index(fields=['loyalty_tier'], name='idx_buyer_loyalty'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['user', 'created_at'], name='idx_activity_user_created'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['action', 'created_at'], name='idx_activity_action_created'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['created_at'], name='idx_activity_created'),
        ),
        migrations.AddIndex(
            model_name='vendorprofile',
            index=models.Index(fields=['business_type'], name='idx_vendor_business_type'),
        ),
        migrations.AddIndex(
            model_name='vendorprofile',
            index=models.Index(fields=['is_verified_vendor'], name='idx_vendor_verified'),
        ),
    ]
