# Generated by Django 5.2.5 on 2025-08-14 07:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_full_name_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_user_id', models.IntegerField(db_index=True)),
                ('username', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('vendor', 'Vendor'), ('buyer', 'Buyer')], max_length=20)),
                ('deleted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('delete_reason', models.TextField(blank=True)),
                ('account_created_at', models.DateTimeField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('wallet_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'verbose_name': 'Archived User',
                'verbose_name_plural': 'Archived Users',
                'indexes': [models.Index(fields=['original_user_id'], name='idx_archived_user_id'), models.Index(fields=['deleted_at'], name='idx_archived_deleted_at'), models.Index(fields=['role'], name='idx_archived_role')],
            },
        ),
    ]
