# Generated by Django 5.2.5 on 2025-08-15 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_buyerprofile_full_name_buyerprofile_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('buyer', 'Buyer'), ('vendor', 'Vendor')], db_index=True, max_length=10)),
                ('email', models.EmailField(db_index=True, max_length=255)),
                ('verification_code', models.CharField(db_index=True, max_length=6)),
                ('expires_at', models.DateTimeField()),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Verification',
                'verbose_name_plural': 'Email Verifications',
                'indexes': [models.Index(fields=['email', 'verification_code'], name='accounts_em_email_30f4ff_idx'), models.Index(fields=['user', 'verified'], name='accounts_em_user_id_98e94d_idx')],
            },
        ),
    ]
