# Generated by Django 5.2.5 on 2025-08-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_emailverification'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='emailverification',
            constraint=models.UniqueConstraint(condition=models.Q(('verified', False)), fields=('user', 'email', 'verified'), name='uniq_active_verification_per_user_email'),
        ),
    ]
