# Generated by Django 5.2.5 on 2025-08-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_passwordreset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='user_type',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('vendor', 'Vendor'), ('admin', 'Admin')], db_index=True, max_length=10),
        ),
    ]
