# Generated by Django 5.2.5 on 2025-09-01 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ForceUpdateConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="production", max_length=100, unique=True),
                ),
                (
                    "minimum_required_version_code",
                    models.PositiveIntegerField(default=1),
                ),
                (
                    "latest_version_name",
                    models.CharField(default="1.0.7", max_length=50),
                ),
                ("latest_version_code", models.PositiveIntegerField(default=1)),
                ("force_update", models.BooleanField(default=False)),
                (
                    "soft_update_version_code",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("play_store_url", models.URLField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Force Update Configuration",
                "verbose_name_plural": "Force Update Configurations",
            },
        ),
    ]
