# Generated by Django 5.2.5 on 2025-09-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("force_update", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreVersionCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("android", "Android (Google Play)"),
                            ("ios", "iOS (App Store)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "app_id",
                    models.CharField(
                        help_text="Package ID for Android, App ID for iOS",
                        max_length=255,
                    ),
                ),
                (
                    "version_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("version_code", models.PositiveIntegerField(blank=True, null=True)),
                ("build_number", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("rate_limited", "Rate Limited"),
                            ("not_found", "Not Found"),
                        ],
                        max_length=20,
                    ),
                ),
                ("response_data", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("checked_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Store Version Check",
                "verbose_name_plural": "Store Version Checks",
                "ordering": ["-checked_at"],
            },
        ),
        migrations.AddField(
            model_name="forceupdateconfig",
            name="android_package_id",
            field=models.CharField(
                blank=True,
                help_text="e.g. com.afrobuyug.app",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="forceupdateconfig",
            name="app_store_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="forceupdateconfig",
            name="auto_fetch_store_info",
            field=models.BooleanField(
                default=False,
                help_text="Automatically fetch latest version info from stores",
            ),
        ),
        migrations.AddField(
            model_name="forceupdateconfig",
            name="ios_app_id",
            field=models.CharField(
                blank=True, help_text="Apple App Store ID", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="forceupdateconfig",
            name="ios_bundle_id",
            field=models.CharField(
                blank=True,
                help_text="e.g. com.afrobuyug.app",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="forceupdateconfig",
            name="ios_latest_build_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="forceupdateconfig",
            name="ios_latest_version_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="forceupdateconfig",
            name="ios_minimum_required_build",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="forceupdateconfig",
            name="ios_soft_update_build",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="forceupdateconfig",
            name="last_store_check",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="forceupdateconfig",
            name="platform",
            field=models.CharField(
                choices=[
                    ("android", "Android"),
                    ("ios", "iOS"),
                    ("universal", "Universal (both platforms)"),
                ],
                default="universal",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="forceupdateconfig",
            name="store_check_interval_hours",
            field=models.PositiveIntegerField(
                default=24, help_text="Hours between automatic store checks"
            ),
        ),
    ]
