# Generated by Django 5.2.5 on 2025-09-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("force_update", "0002_storeversioncheck_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storeversioncheck",
            name="version_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
