# Generated by Django 5.2.5 on 2025-08-21 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InAppNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('vendor', 'Vendor'), ('buyer', 'Buyer')], default='buyer', max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('otp_password_reset', 'OTP Password Reset'), ('otp_verification', 'OTP Verification'), ('general', 'General'), ('order_created', 'Order Created'), ('order_update', 'Order Update'), ('payment_update', 'Payment Update'), ('app_update', 'App Update'), ('return_request', 'Return Request'), ('return_update', 'Return Update')], default='general', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_urgent', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_app_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'in_app_notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
