# Generated by Django 5.2.5 on 2025-08-21 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0002_inappnotifications'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InAppNotifications',
        ),
    ]
