# Generated by Django 5.2.5 on 2025-09-01 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GroupOrder",
        ),
        migrations.RemoveIndex(
            model_name="order",
            name="orders_orde_group_i_5361d5_idx",
        ),
        migrations.RemoveField(
            model_name="order",
            name="group_id",
        ),
    ]
