# Generated by Django 5.2.5 on 2025-09-01 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_delete_grouporder_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="order",
            name="orders_orde_vendor__1aa298_idx",
        ),
        migrations.RemoveField(
            model_name="order",
            name="vendor_id",
        ),
        migrations.AddField(
            model_name="order",
            name="vendor",
            field=models.ForeignKey(
                default=1,
                limit_choices_to={"role": "vendor"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vendor_orders",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("processing", "processing"),
                    ("shipped", "shipped"),
                    ("delivered", "delivered"),
                    ("completed", "completed"),
                    ("cancelled", "cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["vendor"], name="orders_orde_vendor__1aa298_idx"
            ),
        ),
    ]
