# Generated by Django 5.2.5 on 2025-09-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.CharField(db_index=True, max_length=64)),
                ("action", models.TextField()),
                ("user_agent", models.CharField(default="Unknown", max_length=512)),
                ("ip_address", models.CharField(default="Unknown", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Commission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency", models.CharField(max_length=8, unique=True)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_uuid", models.CharField(db_index=True, max_length=64)),
                ("order_id", models.CharField(blank=True, max_length=128, null=True)),
                ("transaction_ref", models.CharField(db_index=True, max_length=128)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("payment_method", models.CharField(max_length=64)),
                ("status", models.CharField(default="completed", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.CharField(db_index=True, max_length=64)),
                ("transaction_ref", models.CharField(max_length=128, unique=True)),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("currency", models.CharField(max_length=8)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "service_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("status", models.CharField(default="pending", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.CharField(db_index=True, max_length=64)),
                ("currency", models.CharField(max_length=8)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
            ],
            options={
                "unique_together": {("uuid", "currency")},
            },
        ),
    ]
