# Generated by Django 5.2.5 on 2025-08-21 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InAppNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('buyer', 'Buyer'), ('vendor', 'Vendor')], max_length=12)),
                ('phone', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('otp_password_reset', 'OTP Password Reset'), ('otp_verification', 'OTP Verification'), ('general', 'General'), ('order_created', 'Order Created'), ('order_update', 'Order Update'), ('payment_update', 'Payment Update'), ('app_update', 'App Update')], db_index=True, max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('is_urgent', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_urgent', '-created_at'],
                'indexes': [models.Index(fields=['user', 'user_type'], name='notificatio_user_id_f0fbbf_idx'), models.Index(fields=['phone'], name='notificatio_phone_70fea8_idx'), models.Index(fields=['type', 'is_read'], name='notificatio_type_68e1af_idx'), models.Index(fields=['-created_at'], name='notificatio_created_dfab23_idx')],
            },
        ),
    ]
